inherits: products.yml

dimensions: 
- alias: from
  values: [ai, bmp, cad, cdr, cf2, cgm, cmx, csv, dcm, dgn, dib, djvu, dng, docm, doc, docx, dotm, dot, dotx, dwf, dwfx, dwg, dwt, dxf, emf, eml, emlx, emz, eps, epub, fodp, fods, gif, html, htm, ico, ifc, igc, igs, j2c, j2k, jls, jp2, jpc, jpeg, jpf, jpg, jpm, jpx, log, mbox, md, mhtml, mht, mobi, mpp, mpt, mpx, msg, odg, odp, ods, odt, one, ost, otg, otp, ots, ott, oxps, pcl, pdf, plt, png, potm, pot, potx, ppsm, pps, ppsx, pptm, ppt, pptx, psd, ps, pst, rtf, stl, svg, svgz, sxc, tex, tiff, tif, tsv, txt, vcf, vdw, vdx, vsdm, vsd, vsdx, vssm, vss, vssx, vstm, vst, vstx, vsx, vtx, webp, web, wmf, wmz, xlam, xlsb, xlsm, xls, xlsx, xltm, xlt, xltx, xml, xps]
- alias: to
  values: [ai, bmp, cgm, csv, dcm, dib, dif, djvu, dng, doc, docm, docx, dot, dotm, dotx, dwf, emf, eml, emlx, emz, epub, fodp, fods, gif, htm, html, ico, igs, j2k, jp2, jpeg, jpf, jpg, jpm, json, ls, md, mht, mhtm, mhtml, mobi, mpp, mpx, msg, odg, odp, ods, odt, otp, ots, ott, pdf, png, pot, potm, potx, pps, ppsm, ppsx, ppt, pptm, pptx, ps, psb, psd, rtf, svg, svgz, sxc, tex, tga, tif, tiff, to, tsv, txt, vdx, vsdm, vsdx, vssm, vssx, vstm, vstx, vsx, vtx, web, webp, wmf, wmz, xer, xlam, xls, xls2003, xlsb, xlsm, xlsx, xlt, xltm, xltx, xml, xps]

dictionaries: ["..\\data\\otherformats.json"]

generationRules:
  include:
  - from[ai] + to[bmp]
  
outputPath: "conversion\\{product}\\{from}-to-{to}.md"
