## CONFIG FOR ANY LOCALIZABLE LANDINGS EXCEPT ENGLISH

inherits: base-config.yml

generationRules:
  exclude:
  - lang[en]
  include:
  - from[ai] + to[bmp]

outputPath: "conversion\\{product}\\{from}-to-{to}.{lang}.md"
